server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://7LYQTPBGIX32UGR:3306/xiaomi?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: provider

  data:
    mongodb:
      uri: mongodb://7LYQTPBGIX32UGR:27017/xiaomi

    elasticsearch:
      #连接的集群名称
      cluster-name: my-application
      #连接的集群节点
      cluster-nodes: 127.0.0.1:9300

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl